config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'

  get 'sessions/new'
  get    'signup'  => 'usuarios#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'dashboard#show'
  post   'dashboard'   => 'sessions#new'
  delete 'logout'  => 'sessions#destroy'

  resources :conta_empresas
  resources :conta_agencia
  resources :feedbacks
  resources :temporarios
  resources :vagas
  resources :agencia
  resources :empresas
  resources :idiomas
  resources :cursos
  resources :formacaos
  resources :experiencia
  resources :clientes
  resources :usuarios
  root 'sessions#new'

end

app/models/agencium.rb
class Agencium < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/conta_agencium.rb
class ContaAgencium < ActiveRecord::Base
end

app/models/conta_empresa.rb
class ContaEmpresa < ActiveRecord::Base
end

app/models/curso.rb
class Curso < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/experiencium.rb
class Experiencium < ActiveRecord::Base
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/formacao.rb
class Formacao < ActiveRecord::Base
end

app/models/idioma.rb
class Idioma < ActiveRecord::Base
end

app/models/temporario.rb
class Temporario < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/models/vaga.rb
class Vaga < ActiveRecord::Base
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :email, :dtNasc, :resumo, :titulo)
    end
end

app/helpers/agencia_helper.rb
module AgenciaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/idiomas_helper.rb
module IdiomasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/vagas_helper.rb
module VagasHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :dtNasc %><br>
    <%= f.date_select :dtNasc %>
  </div>
  <div class="field">
    <%= f.label :resumo %><br>
    <%= f.text_area :resumo %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Dtnasc</th>
      <th>Resumo</th>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.dtNasc %></td>
        <td><%= cliente.resumo %></td>
        <td><%= cliente.titulo %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<p>
  <strong>Dtnasc:</strong>
  <%= @cliente.dtNasc %>
</p>

<p>
  <strong>Resumo:</strong>
  <%= @cliente.resumo %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @cliente.titulo %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>