config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'

  get 'sessions/new'
  get    'signup'  => 'usuarios#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'dashboard#show'
  post   'dashboard'   => 'sessions#new'
  delete 'logout'  => 'sessions#destroy'

  resources :conta_empresas
  resources :conta_agencia
  resources :feedbacks
  resources :temporarios
  resources :vagas
  resources :agencia
  resources :empresas
  resources :idiomas
  resources :cursos
  resources :formacaos
  resources :experiencia
  resources :clientes
  resources :usuarios
  root 'sessions#new'

end

app/models/agencium.rb
class Agencium < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/conta_agencium.rb
class ContaAgencium < ActiveRecord::Base
end

app/models/conta_empresa.rb
class ContaEmpresa < ActiveRecord::Base
end

app/models/curso.rb
class Curso < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/experiencium.rb
class Experiencium < ActiveRecord::Base
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/formacao.rb
class Formacao < ActiveRecord::Base
end

app/models/idioma.rb
class Idioma < ActiveRecord::Base
end

app/models/temporario.rb
class Temporario < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/models/vaga.rb
class Vaga < ActiveRecord::Base
end

app/controllers/idiomas_controller.rb
class IdiomasController < ApplicationController
  before_action :set_idioma, only: [:show, :edit, :update, :destroy]

  # GET /idiomas
  # GET /idiomas.json
  def index
    @idiomas = Idioma.all
  end

  # GET /idiomas/1
  # GET /idiomas/1.json
  def show
  end

  # GET /idiomas/new
  def new
    @idioma = Idioma.new
  end

  # GET /idiomas/1/edit
  def edit
  end

  # POST /idiomas
  # POST /idiomas.json
  def create
    @idioma = Idioma.new(idioma_params)

    respond_to do |format|
      if @idioma.save
        format.html { redirect_to @idioma, notice: 'Idioma was successfully created.' }
        format.json { render :show, status: :created, location: @idioma }
      else
        format.html { render :new }
        format.json { render json: @idioma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /idiomas/1
  # PATCH/PUT /idiomas/1.json
  def update
    respond_to do |format|
      if @idioma.update(idioma_params)
        format.html { redirect_to @idioma, notice: 'Idioma was successfully updated.' }
        format.json { render :show, status: :ok, location: @idioma }
      else
        format.html { render :edit }
        format.json { render json: @idioma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /idiomas/1
  # DELETE /idiomas/1.json
  def destroy
    @idioma.destroy
    respond_to do |format|
      format.html { redirect_to idiomas_url, notice: 'Idioma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idioma
      @idioma = Idioma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idioma_params
      params.require(:idioma).permit(:idCliente, :nomeInstituicao, :titulo, :nivel, :dtInicio, :dtFinal)
    end
end

app/helpers/agencia_helper.rb
module AgenciaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/idiomas_helper.rb
module IdiomasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/vagas_helper.rb
module VagasHelper
end

app/views/idiomas/_form.html.erb
<%= form_for(@idioma) do |f| %>
  <% if @idioma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idioma.errors.count, "error") %> prohibited this idioma from being saved:</h2>

      <ul>
      <% @idioma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idCliente %><br>
    <%= f.text_field :idCliente %>
  </div>
  <div class="field">
    <%= f.label :nomeInstituicao %><br>
    <%= f.text_field :nomeInstituicao %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :nivel %><br>
    <%= f.text_field :nivel %>
  </div>
  <div class="field">
    <%= f.label :dtInicio %><br>
    <%= f.date_select :dtInicio %>
  </div>
  <div class="field">
    <%= f.label :dtFinal %><br>
    <%= f.date_select :dtFinal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/idiomas/edit.html.erb
<h1>Editing Idioma</h1>

<%= render 'form' %>

<%= link_to 'Show', @idioma %> |
<%= link_to 'Back', idiomas_path %>

app/views/idiomas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Idiomas</h1>

<table>
  <thead>
    <tr>
      <th>Idcliente</th>
      <th>Nomeinstituicao</th>
      <th>Titulo</th>
      <th>Nivel</th>
      <th>Dtinicio</th>
      <th>Dtfinal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @idiomas.each do |idioma| %>
      <tr>
        <td><%= idioma.idCliente %></td>
        <td><%= idioma.nomeInstituicao %></td>
        <td><%= idioma.titulo %></td>
        <td><%= idioma.nivel %></td>
        <td><%= idioma.dtInicio %></td>
        <td><%= idioma.dtFinal %></td>
        <td><%= link_to 'Show', idioma %></td>
        <td><%= link_to 'Edit', edit_idioma_path(idioma) %></td>
        <td><%= link_to 'Destroy', idioma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idioma', new_idioma_path %>

app/views/idiomas/new.html.erb
<h1>New Idioma</h1>

<%= render 'form' %>

<%= link_to 'Back', idiomas_path %>

app/views/idiomas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idcliente:</strong>
  <%= @idioma.idCliente %>
</p>

<p>
  <strong>Nomeinstituicao:</strong>
  <%= @idioma.nomeInstituicao %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @idioma.titulo %>
</p>

<p>
  <strong>Nivel:</strong>
  <%= @idioma.nivel %>
</p>

<p>
  <strong>Dtinicio:</strong>
  <%= @idioma.dtInicio %>
</p>

<p>
  <strong>Dtfinal:</strong>
  <%= @idioma.dtFinal %>
</p>

<%= link_to 'Edit', edit_idioma_path(@idioma) %> |
<%= link_to 'Back', idiomas_path %>