config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'

  get 'sessions/new'
  get    'signup'  => 'usuarios#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'dashboard#show'
  post   'dashboard'   => 'sessions#new'
  delete 'logout'  => 'sessions#destroy'

  resources :conta_empresas
  resources :conta_agencia
  resources :feedbacks
  resources :temporarios
  resources :vagas
  resources :agencia
  resources :empresas
  resources :idiomas
  resources :cursos
  resources :formacaos
  resources :experiencia
  resources :clientes
  resources :usuarios
  root 'sessions#new'

end

app/models/agencium.rb
class Agencium < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/conta_agencium.rb
class ContaAgencium < ActiveRecord::Base
end

app/models/conta_empresa.rb
class ContaEmpresa < ActiveRecord::Base
end

app/models/curso.rb
class Curso < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/experiencium.rb
class Experiencium < ActiveRecord::Base
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/formacao.rb
class Formacao < ActiveRecord::Base
end

app/models/idioma.rb
class Idioma < ActiveRecord::Base
end

app/models/temporario.rb
class Temporario < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/models/vaga.rb
class Vaga < ActiveRecord::Base
end

app/controllers/temporarios_controller.rb
class TemporariosController < ApplicationController
  before_action :set_temporario, only: [:show, :edit, :update, :destroy]

  # GET /temporarios
  # GET /temporarios.json
  def index
    @temporarios = Temporario.all
  end

  # GET /temporarios/1
  # GET /temporarios/1.json
  def show
  end

  # GET /temporarios/new
  def new
    @temporario = Temporario.new
  end

  # GET /temporarios/1/edit
  def edit
  end

  # POST /temporarios
  # POST /temporarios.json
  def create
    @temporario = Temporario.new(temporario_params)

    respond_to do |format|
      if @temporario.save
        format.html { redirect_to @temporario, notice: 'Temporario was successfully created.' }
        format.json { render :show, status: :created, location: @temporario }
      else
        format.html { render :new }
        format.json { render json: @temporario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temporarios/1
  # PATCH/PUT /temporarios/1.json
  def update
    respond_to do |format|
      if @temporario.update(temporario_params)
        format.html { redirect_to @temporario, notice: 'Temporario was successfully updated.' }
        format.json { render :show, status: :ok, location: @temporario }
      else
        format.html { render :edit }
        format.json { render json: @temporario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temporarios/1
  # DELETE /temporarios/1.json
  def destroy
    @temporario.destroy
    respond_to do |format|
      format.html { redirect_to temporarios_url, notice: 'Temporario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temporario
      @temporario = Temporario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def temporario_params
      params.require(:temporario).permit(:idvaga, :idcliente, :inscrito, :preselecionado, :efetivado)
    end
end

app/helpers/agencia_helper.rb
module AgenciaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/idiomas_helper.rb
module IdiomasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/temporarios_helper.rb
module TemporariosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/vagas_helper.rb
module VagasHelper
end

app/views/temporarios/_form.html.erb
<%= form_for(@temporario) do |f| %>
  <% if @temporario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temporario.errors.count, "error") %> prohibited this temporario from being saved:</h2>

      <ul>
      <% @temporario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idvaga %><br>
    <%= f.text_field :idvaga %>
  </div>
  <div class="field">
    <%= f.label :idcliente %><br>
    <%= f.text_field :idcliente %>
  </div>
  <div class="field">
    <%= f.label :inscrito %><br>
    <%= f.text_field :inscrito %>
  </div>
  <div class="field">
    <%= f.label :preselecionado %><br>
    <%= f.text_field :preselecionado %>
  </div>
  <div class="field">
    <%= f.label :efetivado %><br>
    <%= f.text_field :efetivado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/temporarios/edit.html.erb
<h1>Editing Temporario</h1>

<%= render 'form' %>

<%= link_to 'Show', @temporario %> |
<%= link_to 'Back', temporarios_path %>

app/views/temporarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Temporarios</h1>

<table>
  <thead>
    <tr>
      <th>Idvaga</th>
      <th>Idcliente</th>
      <th>Inscrito</th>
      <th>Preselecionado</th>
      <th>Efetivado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temporarios.each do |temporario| %>
      <tr>
        <td><%= temporario.idvaga %></td>
        <td><%= temporario.idcliente %></td>
        <td><%= temporario.inscrito %></td>
        <td><%= temporario.preselecionado %></td>
        <td><%= temporario.efetivado %></td>
        <td><%= link_to 'Show', temporario %></td>
        <td><%= link_to 'Edit', edit_temporario_path(temporario) %></td>
        <td><%= link_to 'Destroy', temporario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Temporario', new_temporario_path %>

app/views/temporarios/new.html.erb
<h1>New Temporario</h1>

<%= render 'form' %>

<%= link_to 'Back', temporarios_path %>

app/views/temporarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idvaga:</strong>
  <%= @temporario.idvaga %>
</p>

<p>
  <strong>Idcliente:</strong>
  <%= @temporario.idcliente %>
</p>

<p>
  <strong>Inscrito:</strong>
  <%= @temporario.inscrito %>
</p>

<p>
  <strong>Preselecionado:</strong>
  <%= @temporario.preselecionado %>
</p>

<p>
  <strong>Efetivado:</strong>
  <%= @temporario.efetivado %>
</p>

<%= link_to 'Edit', edit_temporario_path(@temporario) %> |
<%= link_to 'Back', temporarios_path %>