config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'

  get 'sessions/new'
  get    'signup'  => 'usuarios#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'dashboard#show'
  post   'dashboard'   => 'sessions#new'
  delete 'logout'  => 'sessions#destroy'

  resources :conta_empresas
  resources :conta_agencia
  resources :feedbacks
  resources :temporarios
  resources :vagas
  resources :agencia
  resources :empresas
  resources :idiomas
  resources :cursos
  resources :formacaos
  resources :experiencia
  resources :clientes
  resources :usuarios
  root 'sessions#new'

end

app/models/agencium.rb
class Agencium < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/conta_agencium.rb
class ContaAgencium < ActiveRecord::Base
end

app/models/conta_empresa.rb
class ContaEmpresa < ActiveRecord::Base
end

app/models/curso.rb
class Curso < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/experiencium.rb
class Experiencium < ActiveRecord::Base
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/formacao.rb
class Formacao < ActiveRecord::Base
end

app/models/idioma.rb
class Idioma < ActiveRecord::Base
end

app/models/temporario.rb
class Temporario < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/models/vaga.rb
class Vaga < ActiveRecord::Base
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:idcliente, :idusuario, :descricao, :nota, :idvaga)
    end
end

app/helpers/agencia_helper.rb
module AgenciaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/idiomas_helper.rb
module IdiomasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/vagas_helper.rb
module VagasHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idcliente %><br>
    <%= f.text_field :idcliente %>
  </div>
  <div class="field">
    <%= f.label :idusuario %><br>
    <%= f.text_field :idusuario %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :nota %><br>
    <%= f.text_field :nota %>
  </div>
  <div class="field">
    <%= f.label :idvaga %><br>
    <%= f.text_field :idvaga %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Idcliente</th>
      <th>Idusuario</th>
      <th>Descricao</th>
      <th>Nota</th>
      <th>Idvaga</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.idcliente %></td>
        <td><%= feedback.idusuario %></td>
        <td><%= feedback.descricao %></td>
        <td><%= feedback.nota %></td>
        <td><%= feedback.idvaga %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idcliente:</strong>
  <%= @feedback.idcliente %>
</p>

<p>
  <strong>Idusuario:</strong>
  <%= @feedback.idusuario %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @feedback.descricao %>
</p>

<p>
  <strong>Nota:</strong>
  <%= @feedback.nota %>
</p>

<p>
  <strong>Idvaga:</strong>
  <%= @feedback.idvaga %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>